#!/usr/bin/python
# -*- coding: utf-8 -*-
# ui/constants.py

BUTTON_PINS = {
    "enter": 23,
    "left": 24,
    "up": 25,
    "right": 8,
    "down": 7,
}

RIGHT_ARROW = "\x02"
LEFT_ARROW = "\x03"
UP_ARROW = "\x04"
DOWN_ARROW = "\x05"
DEGREE_CHAR = "\x06"

UI_MODE_HOME = "HOME"
UI_MODE_CONFIRM = "CONFIRM"
UI_MODE_MENU = "MENU"
UI_MODE_STATUS = "STATUS"
UI_MODE_EDITOR = "EDITOR"
UI_MODE_PROGRAMS = "PROGRAMS"
UI_MODE_PROGRAM_DETAILS = "PROGRAM_DETAILS"
UI_MODE_PROGRAM_ACTIONS = "PROGRAM_ACTIONS"
UI_MODE_PROGRAM_EDIT = "PROGRAM_EDIT"
UI_MODE_DAYS_EDITOR = "DAYS_EDITOR"
UI_MODE_DATETIME_EDITOR = "DATETIME_EDITOR"

UI_MODE_SPECIAL_PROGRAMS = "SPECIAL_PROGRAMS"
UI_MODE_SPECIAL_PROGRAM_DETAILS = "SPECIAL_PROGRAM_DETAILS"
UI_MODE_SPECIAL_PROGRAM_EDIT = "SPECIAL_PROGRAM_EDIT"

UI_MODE_HOLIDAY_PROGRAMS = "HOLIDAY_PROGRAMS"
UI_MODE_HOLIDAY_PROGRAM_DETAILS = "HOLIDAY_PROGRAM_DETAILS"
UI_MODE_HOLIDAY_PROGRAM_EDIT = "HOLIDAY_PROGRAM_EDIT"

DISPLAY_WIDTH = 16
DISPLAY_LINES = 4

CONFIRM_TIMEOUT_SECONDS = 5.0

MENU_TIMEOUT_SECONDS = 60